name: Update Dashboard
on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install requests pandas plotly
      - run: python chess.py
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add index.html
          git commit -m "Update dashboard" || echo "No changes"
          git push
